### ISSUE TITLE
Add ability to start a process, so can get a memplot of cmd line programs

### ISSUE THREAD

**Issue by james-antill** [0x0f0f0f/memplot#1]
Connecting via. pid is great for services, but doesn't work well for applications that you start on the command line.

**Comment by 0x0f0f0f** [comment]
Added in 7fb7943c9cb2cdc2c7f16103c0ea394a263ffc22 
Just published v0.1.0 with this feature.
Simply add the name of the program and its arguments after the options when launching memplot.
Note that the `-pid` flag and a program argument are mutually exclusive. 
Next, would be making memplot ignore duration and plot for the whole execution time of the child program
