### ISSUE TITLE
Installation installs memplot as "cmd"

### ISSUE THREAD

**Issue by james-antill** [0x0f0f0f/memplot#2]
Installation instructions are:

    go get -u -v github.com/0x0f0f0f/memplot/cmd

...this installs a binary called "cmd", much like if you cd to that dir. and "go build". Usual layout I use is:

    github.com/<user>/<repo>/cmd/memplot/memplot.go

...then:

    go get -u -v github.com/0x0f0f0f/memplot/cmd/memplot

..will give you a memplot binary. There might be a more efficient way to do this but, I keep using the same thing because it works :).

**Comment by 0x0f0f0f** [comment]
fixed in b25b60279796aea85d291f39afaf687437d5dd01
