### ISSUE TITLE
panic if the spawned command exits with a non-zero exit code

### ISSUE THREAD

**Issue by sbrl** [0x0f0f0f/memplot#3]
Hey, loving the improvements! The auto-spawning a command makes it much easier to use, and the SVG output option lets you zoom in a let a closer look.

I found a panic though. If the spawned command exits with a non-zero exit code, `memplot` panics:

```
panic: exit status 64

goroutine 18 [running]:
main.check(...)
	/home/runner/work/memplot/memplot/cmd/memplot.go:16
main.main.func2(0xc000012090, 0x3, 0x3, 0xc00018e000)
	/home/runner/work/memplot/memplot/cmd/memplot.go:86 +0xfe
created by main.main
	/home/runner/work/memplot/memplot/cmd/memplot.go:80 +0x4e8
```

**Comment by 0x0f0f0f** [comment]
fixed in e42efef76fccd6aad1711ff644aa7c7e6701aedc
